#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

language: java
install: true
jdk:
  - openjdk8

stages:
  - name: build

jobs:
  include:
    - stage: build
      script: scripts/build-installer.sh

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file: build/installer/flink-tools-*.tgz
  edge: true # opt in to dpl v2
  on:
    tags: true
