{{- define "flink-app-library.flinkapp" -}}
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkCluster
metadata:
  labels:
    name: {{ $.Release.Name }}
  name: {{ $.Release.Name }}
spec:
  imageRef:
    name: {{ $.Values.imageRef.name }}
  jobManager:
    cpu: 250m
    memory: 1024M
    replicas: 1
  localStorage:
    replicas: {{ .Values.localStorage.replicas }}
    volumeClaimTemplate:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: {{ .Values.localStorage.size }}
      storageClassName: standard
  storage:
    volumeSource:
      persistentVolumeClaim:
        claimName: data-project

  taskManager:
{{ toYaml .Values.taskManager | indent 4 }}

{{- if .Values.clusterConfiguration }}
  configuration:
{{ toYaml .Values.clusterConfiguration | indent 4 }}
{{- end }}

{{- if .Values.logging }}
  logging:
{{ toYaml .Values.logging | indent 4 }}
{{- end }}

  zookeeperUrl: zookeeper-client:2181
---
apiVersion: flink.nautilus.dellemc.com/v1beta1
kind: FlinkApplication
metadata:
  labels:
    release: {{ $.Release.Name }}
  name: {{ $.Release.Name }}
spec:
  clusterSelector:
    name: {{ $.Release.Name }}
  flinkVersion: {{ .Values.flinkVersion }}
  mainClass: {{ .Values.mainClass }}
  mavenCoordinate: {{ .Values.mavenCoordinate.group }}:{{ .Values.mavenCoordinate.artifact }}:{{ .Values.mavenCoordinate.version }}
  parallelism: {{ .Values.parallelism }}
  parameters:
    - name: scope
      value: {{ $.Release.Namespace | quote }}
    - name: jobName
      value: {{ $.Release.Name | quote }}
    {{- range $key, $value := .Values.appParameters }}
    - name: {{ $key | quote }}
      value: {{ $value | quote }}
    {{- end }}
  state: started
{{- end -}}
